name: Run Automation Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Website Repository
      uses: actions/checkout@v2
      with:
        repository: 'AxelAlinsky/realworld-app'

    - name: Checkout Automation Repository
      uses: actions/checkout@v2
      with:
        repository: 'AxelAlinsky/realworldApp-workspace-automation'
        path: 'realworldApp-workspace-automation'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: |
        cd realworldApp-workspace-automation
        npm install

    - name : Build Automation Scripts
      run: |
        npm run build

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run Automation Tests
      run: |
        npm run regression
